# Config -----------------------------

name: simurai
description: simurai's site
url: http://simurai.com

permalink: /:categories/:year/:month/:day/:title

kramdown:
  input: GFM

# exclude: [archive, cursor-monster, letter-heads]
